### ISSUE TITLE
local.gradle' as it does not exist

### ISSUE THREAD

**Issue by apples398** [divvun/giella-ime#1]
Error:(2, 0) Could not read script 'F:\gh_project\IME\giella-ime-master\app\local.gradle' as it does not exist.
<a href="openFile:F:\gh_project\IME\giella-ime-master\app\build.gradle">Open File</a>

**Comment by bbqsrc** [comment]
GiellaIME is not designed to be used without `kbdgen` at the moment.

You'll need to create a `local.gradle` file that has the format below:

```
ext.app = [
            storeFile: "{store_file}",
            keyAlias: "{key_alias}",
            packageName: "{pkg_name}",
            versionCode: {build},
            versionName: "{version}"
]
```

**Comment by apples398** [comment]
Error:(13, 1) A problem occurred evaluating project ':app'.
> Could not find method versionCode() for arguments [local_8e4eghhxsy0prrlic34on9c6x$_run_closure1@746455f1] on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=14, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=23, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=com.android.inputmethod.latin, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
