### ISSUE TITLE
Samiske tastaturer v. 1.1.2 crashes constantly

### ISSUE THREAD

**Issue by albbas** [divvun/giella-ime#3]
I installed v1.1.2 today, and it crashes constantly when I try to activate it. The only way to get a  working keyboard is to uninstall v.1.1.2.
v.1.1.1 worked for me.

I have a Moto G4 Plus, with Android 7.0 on it.

**Comment by albbas** [comment]
I also installed the Nivkh keyboard, and it worked  without problems.

**Comment by snomos** [comment]
A new beta with better crash logging and debugging features (based on sentry) built in will be release later today. With the information gathered then, it should hopefully be possible to fix the bug.

**Comment by albbas** [comment]
I was offered 1.2.0 in Google Play now and installed it. Works without crashes for me™.

**Comment by snomos** [comment]
Fixed in 1.2.0?
